//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAbgAAAG4CAIAAAC4qGXkAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P35j2TJlt+JhYdv4R57Ru61Za1v7252s9lkk90jCRDJGQoQBpAg/SIIgjQjskkK+j8EzW8zEAQIgiBgJAEDcDikIGHYmkaT7G72+rrfq3qvlleVWZVVmRmZGbvvW+jz/R671697LBmZlVlVr5vfsLhuduzYsWPHzI6ZXb/uXvrZzz5cWFhYLJVKvBRQJDheOi5wRC7XY70scC3yIy3FiJcXU4z4YplrqaRreRG6xBJMR4riIef4eKICZ2Iqf4rSjA7SzUKOj6Xj8WRCC4LurGO/ogPRyWg0HAwGo9FYJYM0GXMZ+w8CJBo1Hk8Gwz7JlZWVWrU6RqYMhzQXIZsXJIcFVFtWe1z5DwWJmUIRFZgcSzcX5moO4ViCI5KEOWWTZSkK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abyssinian {
            get {
                return ResourceManager.GetString("Abyssinian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAIAAAD2HxkiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1pkyRZlqaH2aqL7eZr7LlVVVd1T88MBwMhIaSQQkCAL6QQGM4M+AP5hR/4DygcgMBwGj3TXb1XZeUem+/mtutuanjec809PCLdPSMyIrKyquuEhrkuV+9y7nnPcu9V1er/8//1/65Uq+v1urJeV6tV9tmpXCFduqDqulpbV9kpqyV/19xXXZe6wdKUdU4pmQ51hgOS6NK36Gq20A2p3pZeKkXN+8dIr7D6dnpPHPshsn2Zbi/kTXjyBtV9JdvylhuFmU3imvvz+nS1EIosS0PvxYnN3ysEsg2u2n15+wP9Y6U/dP7L9OYgrBq+DXbYzVpVmwyofnSd7RJnpbZqWamtzSIC2kvS/X+gf6S0kQFHm3P/iOnNQPiKyRPyOAMjy7Ky [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oriental {
            get {
                return ResourceManager.GetString("Oriental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAe8AAAHvCAIAAADy68CaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhedP3pliRJji/4+Warr7FlZGZVdQ+7D4dnXmDe/x3ID/wwvIe3l6rOzMgIX23zjb8/oKbhmX2JsFAXhUAgAAQCgaiqqR3+H//H/+Og4Ojo6LWgTw8PDx3HUzCWiyrlpunjgdbHzy9HL0eHh68vL4ev0EezyXw6mWzW28V8MZvMdLGYLSYnk+vr699++2Uxn/3w04/z2eLL199/+/Lby+vr8vRsMpkeTaYn0+m//cd/bHePl5fvTs/Pnh53//i3f5+dnPzf/uVfnp+ff/vty8nJyQ8/fFouTx8eHr59/fr09PTTTz9Bqv2Xf/3X2elysjz9/Je/LufLx83qabv7x7//+//7//X//O2//nF3c3N0+DqfT+eTycvLy263psnx8cmOSiT2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RussianBlue {
            get {
                return ResourceManager.GetString("RussianBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAVgAAAFYCAIAAACZDnMXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P3nt+RWluUJmoQGTD7pz7WTdDIogqEzIyMrszqn1pq/e9Z8mKnuqapUEQwq10+aNgAGk/PbB89JZtV0r5rudH+MCL9ubs8MBnFxxD77XIVq5U+wVH9Q61pNX3Y7Xjt+4b1a1Xv567vyrryF8toIZXcYJ696TYVtjWaz3qhXdtXVarNaFdvtFgv9Edpn/frvn1pByHUJu1JFxrVqvS735z+b3oHAu/I2S6Necz230ZDb88ImS+N0nGajISM1iKgIAoQCZcT60ZU/JSDAzyklH0CYhrt4fhVpN+vcCDKu1PTrO0bwrrypUhphE++3r9ge/k7UL01REEBYEhBUXcdxXYedt9vNdrMxFNjttjsM9EdonXKqP5UiCRoKlI6OzzfrVXRQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Savannah {
            get {
                return ResourceManager.GetString("Savannah", resourceCulture);
            }
        }
    }
}
