//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAIAAABEtEjdAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P3peiQ5kqaJmulqK+nuEZGZXVVdlUvNXZzp7npmpu//As6veWZOV1VmhLuTtFUXO+8nAoWpqS0kfYmIzPSPSjWIQLADAgF0G/8f//3/MxpiPB6nnAMlHOyIaEfjNjglnYwPR+F2nLSjJBAjuZKDhImUM4KNyUKOLYlxF7ExDsSltHCa/OhwkpNMKR1zMk4S5AIhKLXgFAbZHuJwuOXbHtq+d6qUjmnJy6iQzw6R7FXJEIRVnZnb5VMICh1LPaacx/DnSSR9TpqMU2pplGWZvJKkzMs8z9umhYSZZubLj4nhxRmxJFVd5dnEAiVIWiRpkpwkDXB42EgiL+8zuG+E1zBnd7TtsdvAbtv6QF/qQDfpN4jq/7SBnBwkMUCiujkXgJP0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abyssinian {
            get {
                return ResourceManager.GetString("Abyssinian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe1P1bkyxLlt+H5f1Stfc+ffo2M4BRHwszoHAX8KLPJpHUm0BSJpJGMxlMb6LpnRSNJg0wg+4+e1dV3lO/33+5R0ZW1d7nnJ4GRK2KinBfvm6+3H25e2Rk5PS//L//P6fT6WQEZoIp/FB6vV5ns9nkmkKwwHUyy5VSiiCgIGTT+XzeuCbXWQSEcMpFlmTnsznKZiBmlF8WsxlcyEEs5Zfr5HL173y9XCIZWSXoer3IAAXyvVyRyznCZwtkcEyQT17D0HU6nasel8sFJXNthwvbxDZrrybgRTFYpJflsHBdzOfT2ex8PoMhi9rT6YRdsCAfLbBitWm9kfpKGhEjKLR4KzWCFLSKdCDT6H8OFD++y/UO0kY/BhcbcaBDztkmaWZcccb0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Angora {
            get {
                return ResourceManager.GetString("Angora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAdkAAAHZCAIAAABFJdZVAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1XkyVJmiWImSkzfonTIEmLdVeTYTsQCCDAG4AniOAPYLG/YCCygz+EJwAPK2A7s7KCXWBnure7Z3qquotmVSWJzODOLjduamY4n9p1DyfXabhHRmb5CYvrZmpqyvXoUTU1Vft/+Py59Xaw6T/93Bj2FR5face2WhzLi9tG5+5duW6A0N8l4PodetC2VnO11IGtS2O6yqX2rVK/RQBvBzdzqTn21InYH0uL48lyoiS3KO/Le50dOAaDo1/8M8c1sDIWZw0PTUzdOo4zNW3Fs/hPwTttfgS6sfKpVY8cN0e86Tj77Dl+wRT2lxer8OZBiuYbmyZpl+eHOHaXbnW3T1sCjp6loOKhU269uaS4mBPCUUhY9+ce97jHPe7xLeKei+9x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bengal {
            get {
                return ResourceManager.GetString("Bengal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAXwAAAF8CAIAAABDhZedAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P33kyTJlecJOuc8eCTPyqzMLAZUFWg1753ekfthZP+B3f9l/qg7kbsTmd2Vm240AbqB4pU8g0c4J2Zu5vw+36eegURVF2bQADKiIK7p6WFupqb69JHve0/NTC26WCwiq7Iqq7Iqr6vEln9XZVVWZVVeS1mBzqqsyqq81rICnVVZlVV5rWUFOquyKqvyWssKdFZlVVbltZYV6KzKqqzKay0r0FmVVVmV11pWoLMqq7Iqr7WsQGdVVmVVXmtZgc6qrMqqvNayAp1VWZVVea1lBTqrsiqr8lrLCnRWZVVW5bWWFeisyqqsymstK9BZlVVZlddaVqCzKquyKq+1rEBnVVZlVV5rWYHOqqzKqrzWsgKdVVmVVXmtZQU6q7Iqq/Jaywp0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Birman {
            get {
                return ResourceManager.GetString("Birman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAXsAAAF7CAIAAAC8XLxcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P3nkyVJut6JHRFxtBapKrNUq2k1c0fu3AsCF7hLAl+45O7yA0mzNa4taeRX7ieYwQy4wF9Ao9FsbZcEzWgQC+6Ci3uBe3HFiJ6Z7tHdPdPTWlSXSp15tD4RR/H3uGdGn86sqq7p7uqZGvRbpyI9PDxcvv7483p4eITn83now7JYLMLhMEfrOPH9sNhLNhin1mE9zwcIPO9f7F2K8e6320s2GKfWYT2Dq4H/3QLg5C9uPKgKUxvhSIRqmS4W80jY8X3CSqbTaSwWI9hgMNzZ2en1evl8wXUdbzxaW1vLpLMTfxaLx6JRx0YfjUZwhsILxUj0J3n5INuEMb6cEiRiEvmQ2JAcrePE98NiL9lg1se6rf+ZANbn1xJ7l6K7++32kg3G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bombay {
            get {
                return ResourceManager.GetString("Bombay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P33k11Hkid6ptYSWgMEQFUssrpkz7zunbF5Y293zPaPWVt7b3q6p3tm/6b95dmzHdHTPa2quhSLEiChZQokUmuxHw8/9+TNm5kgSKKqwCKclwd+PDw8PPyEf4/HySvaF5fW2tt32tra2tvbHQuz09betrMdrP93dqLVMZmkZj6JhIU00tHRUdRDB1/aK/v1sdIvTc+m7W2uUN9Og0m6shwWmqhqK1R6BWWv5r4Hku66OKZZPCb5VEiD2bQVtLmxsb5ZaGlpaXV1lSi8LOSf0smgelRT7izkzCC12cOoReEL9fdTy8Rr35I2TWBzk5DbTnc9b+gnn6d0aglPUm4uGSJU5hWUvGOqpSRPTSCZYj4DU7U60xDHQmGtHJNIsm+jU6XJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string British {
            get {
                return ResourceManager.GetString("British", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAaIAAAGiCAIAAAAqaVU4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1pk6RHkif4xeF3eNxHnjgLqLu6u7p7dincQ4SyK6TwFb8ARfiCIuQ7fgHO8MPw5cq+WsoKl7LTuzM9093T0/d0FQqFK+/MuO9w97j5U1MPRyAzASQKCSAS5YqApT1mampqZqr/R+25fLR3eDpyic7Pz/u5r0WEfEbO6OhoP/f59CI83xp9sSpfquqXMryUWf4C+oYn83z0C0fw9Xu/Usbwe0gvCQeeQ0wn0jOZyH3TjpA01v93SEMa0pC+pzSEuSENaUjfc/oMzH1zkeqX0iu0SflSVX/PN1zD/eaQrhoNo7khDWlI33N6mTDnNP551OcY0pCGNKRvnYbR3JCGNKTvOQXMnV9QFv0O9PsTsg0j08+jtAHUPx7SkK4MDaO5IQ1p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Burmilla {
            get {
                return ResourceManager.GetString("Burmilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAIAAABEtEjdAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1nkyRJliWKubsx5yxoZiStLN7VvGeW4e17kMUTfMTOzn7A33sCfIMAIlgR4EEggLwevN3Znekh3T09VV08eWZw58zM3HHOvWrm5izCIzIiM6u6TmiYqym9elX16FUzc/P0//R//p9SqVQmncZxEePJRD0T8ehRPGP1AOl0xvhmoWkmY5MFiLNfCLEMQLKEWf9UniRW1ZiUKonF9iZLnitNC0mKtxRzuSLMlJxO6H9FetWzScbM49D3AxxPTk5brdbx0VGj2Tw8PDw5OW6cNvzAtyxbUyaOy7V0GUwiUWaBwPQ5+iBWtTGJxXJ0lEq9EyuTjlNkLChHXVrSTOxMyrXSrpXy7Aw8dkbSp8YyVJdUTXEmUjD9oqX0BKUhOIQL08E4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Munchkin {
            get {
                return ResourceManager.GetString("Munchkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAIAAAD2HxkiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1pkyRZlqaH2aqL7eZr7LlVVVd1T88MBwMhIaSQQkCAL6QQGM4M+AP5hR/4DygcgMBwGj3TXb1XZeUem+/mtutuanjec809PCLdPSMyIrKyquuEhrkuV+9y7nnPcu9V1er/8//1/65Uq+v1urJeV6tV9tmpXCFduqDqulpbV9kpqyV/19xXXZe6wdKUdU4pmQ51hgOS6NK36Gq20A2p3pZeKkXN+8dIr7D6dnpPHPshsn2Zbi/kTXjyBtV9JdvylhuFmU3imvvz+nS1EIosS0PvxYnN3ysEsg2u2n15+wP9Y6U/dP7L9OYgrBq+DXbYzVpVmwyofnSd7RJnpbZqWamtzSIC2kvS/X+gf6S0kQFHm3P/iOnNQPiKyRPyOAMjy7Ky [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oriental {
            get {
                return ResourceManager.GetString("Oriental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAe8AAAHvCAIAAADy68CaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhedP3pliRJji/4+Warr7FlZGZVdQ+7D4dnXmDe/x3ID/wwvIe3l6rOzMgIX23zjb8/oKbhmX2JsFAXhUAgAAQCgaiqqR3+H//H/+Og4Ojo6LWgTw8PDx3HUzCWiyrlpunjgdbHzy9HL0eHh68vL4ev0EezyXw6mWzW28V8MZvMdLGYLSYnk+vr699++2Uxn/3w04/z2eLL199/+/Lby+vr8vRsMpkeTaYn0+m//cd/bHePl5fvTs/Pnh53//i3f5+dnPzf/uVfnp+ff/vty8nJyQ8/fFouTx8eHr59/fr09PTTTz9Bqv2Xf/3X2elysjz9/Je/LufLx83qabv7x7//+//7//X//O2//nF3c3N0+DqfT+eTycvLy263psnx8cmOSiT2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RussianBlue {
            get {
                return ResourceManager.GetString("RussianBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAVgAAAFYCAIAAACZDnMXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P3nt+RWluUJmoQGTD7pz7WTdDIogqEzIyMrszqn1pq/e9Z8mKnuqapUEQwq10+aNgAGk/PbB89JZtV0r5rudH+MCL9ubs8MBnFxxD77XIVq5U+wVH9Q61pNX3Y7Xjt+4b1a1Xv567vyrryF8toIZXcYJ696TYVtjWaz3qhXdtXVarNaFdvtFgv9Edpn/frvn1pByHUJu1JFxrVqvS735z+b3oHAu/I2S6Necz230ZDb88ImS+N0nGajISM1iKgIAoQCZcT60ZU/JSDAzyklH0CYhrt4fhVpN+vcCDKu1PTrO0bwrrypUhphE++3r9ge/k7UL01REEBYEhBUXcdxXYedt9vNdrMxFNjttjsM9EdonXKqP5UiCRoKlI6OzzfrVXRQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Savannah {
            get {
                return ResourceManager.GetString("Savannah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAiYAAAImCAIAAADorNYRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1Xlx9HkiZ4J5DQGiRBTVYVu7pqqkecme2ZvZmb+TTb+0n34t1z9mL6TPeIrimKogBIaJHIRCby/bk/ns7IiL9KBVHFp1ne5uZmj5l7RJj9IxVO/V//1/+1tgy7u7vGU6dOZToPMw34xj1gYzq07KuL+eMY4+4SjKanT59u0qEwYhM3odt8FoarjCMMlZH70kHBvbMdlKo7ruKygLxkcLRdrIjFUbJ6IMx0mccj7mhp9YixHGY+1Lx8+bLqlt+fMyMmMSQzT6Yre5RVcCDjEXqShGlKw9UI0M26y9B3aNkx0x3ogWbqPjTLccWyqfYsXYWl2++cMA20GDHLOIw+hTQkM7Lc2dmZ3idLQ8cdIUtyxiwNkb2P2GI/Uo6mC9Athy6F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scottish {
            get {
                return ResourceManager.GetString("Scottish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAk4AAAJOCAIAAADOOx+iAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhevP33l2RZcueJRbjWKtxDp67M0q0b3WjMAFiowZKD3cEAHMzuYjkD7ix2xA97Dg/Jc0j+T+Th8pcd7pAY6EZPV6vqqsqsrMzI0Do8XGsPfr5m73l4pOjus8rixvP7rrBrZteu2bX3nj9f/FI2urCwcLXIYWGycKX8VPmX4OpqcTINKmg0XYxYdnp1pS4/AyI36xcXF39uFwda2qcGopPlr2HqlQbzCGd552gGkYWb5yFEriJ08V6TuT4mhAgsU4FYGI5KyiaGxxteqVKU0H26sDhVMxeLwBmfXk0jiwteDEdABDDWFiPko8bmdS87nfEuiNKGDnMlV3PtZ8BMcHRGXoL5vvMQnZPJjTaw8jpw5IGqvG44ZgmuqRe9onIqumF51sok [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Siberian {
            get {
                return ResourceManager.GetString("Siberian", resourceCulture);
            }
        }
    }
}
